# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package.json and lock file
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the files
COPY . .

# Expose port if necessary (not needed for stdio transport but if you want for API usage, expose 3000)
EXPOSE 3000

# Start the server
CMD ["node", "server.js"]
